name: sofa_gas_buddy
description: "A helper for the AAFES gas program in Germany"
publish_to: 'none'
version: 1.0.0+1 #Don't change this, Gradle automatically updates the build/version number.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  requests: ^4.7.0
  flutter_secure_storage: ^10.0.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.5
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: "^2.3.10"

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/appicon_filled.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/appicon_background.png"
  adaptive_icon_foreground: "assets/appicon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_screen.png
  color_dark: "#000000"
  image_dark: assets/splash_screen.png

  android_12:
    image: assets/appicon_filled.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/appicon_filled.png
    icon_background_color_dark: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/appicon.png
    - assets/appicon_filled.png
    - assets/appicon_foreground.png
    - assets/splash_screen.png
    - assets/appicon_background.png
